# Generated by Django 5.2.1 on 2025-06-21 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_events_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="picture",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
    ]
