# Generated by Django 5.2.1 on 2025-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.FileField(default=None, upload_to="uploads/"),
        ),
    ]
