# Generated by Django 5.2.1 on 2025-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.FileField(
                blank=True, default="uploads/default.webp", upload_to="uploads/"
            ),
        ),
    ]
