# Generated by Django 5.2.1 on 2025-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
