# Generated by Django 5.2.1 on 2025-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.ImageField(
                blank=True, default="uploads/default.webp", upload_to="uploads/"
            ),
        ),
    ]
