# Generated by Django 5.2.1 on 2025-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
